<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
    <Description>The Cauldron Fan Expansion for the Sentinels of the Multiverse Digital Card Game.</Description>
    <Version>2.4.0</Version>
    <RequiresEngineDeps>true</RequiresEngineDeps>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="DeckLists\**\*.json" />
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <EmbeddedResource Include="DeckLists\**\*.json">
      <LogicalName>Cauldron.DeckLists.%(EmbeddedResource.FileName).json</LogicalName>
    </EmbeddedResource>
    <Content Include="manifest.json">
	    <Link>manifest.json</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="copy /Y &quot;$(TargetDir)$(TargetName).dll&quot; &quot;$(DeployPath)/$(TargetName).dll&quot;&#xD;&#xA;copy /Y &quot;$(TargetDir)manifest.json&quot; &quot;$(DeployPath)/manifest.json&quot;" />
  </Target>

  <Target Name="DebugGlobalVars" BeforeTargets="PrepareForBuild">
    <Message Importance="high" Text="=== DEBUGGING MSBUILD ENGINE SETUP ===" />
    <Message Importance="high" Text="Project Name:      $(MSBuildProjectName)" />
    <Message Importance="high" Text="RequiresEngineDeps:  $(RequiresEngineDeps)" />
    <Message Importance="high" Text="EngineDepsPath:      $(EngineDepsPath)" />
    <Message Importance="high" Text="DeployPath:      $(DeployPath)" />
    <Message Importance="high" Text="======================================" />
  </Target>
</Project>
