<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Automated tests for the Cauldron Fan Expansion for the Sentinels of the Multiverse Digital Card Game.</Description>
    <RequiresEngineDeps>true</RequiresEngineDeps>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.17.0" />
    <PackageReference Include="Troschuetz.Random" Version="5.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CauldronMods\CauldronMods.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <ProjectPathPath>$(ProjectDir)path.cs</ProjectPathPath>
  </PropertyGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="echo namespace CauldronTests { static public class ProjectPath { public static readonly string Path = @&quot;$(ProjectDir)&quot;;} } &gt; $(ProjectPathPath)" />
  </Target>

  <Target Name="AddProjectPathClass" AfterTargets="PreBuildEvent" BeforeTargets="BeforeCompile;CoreCompile">
    <ItemGroup>
      <Compile Include="$(ProjectPathPath)" />
    </ItemGroup>
  </Target>
</Project>
