name: 'Set Up Dependencies'
description: 'Sets up dependencies for Sentinels Steam Mods'
inputs:
  checkout_path:
    description: 'Where to check out dependencies'
    required: false
    default: 'deps'
  dependency_app_id:
    description: 'The App ID of the Github App for fetching dependencies'
    required: true
  dependency_private_key:
    description: 'The Private Key of the Github App for fetching dependencies'
    required: true
  dependency_repo_name:
    description: 'The name of the dependency reposiitory'
    required: true
  dependency_repo_organization_name:
    description: 'The name of the organization where the dependency repository lives'
    required: true
runs:
  using: "composite"
  steps:
    - name: Generate GitHub App Token
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ inputs.dependency_app_id }}
        private-key: ${{ inputs.dependency_private_key }}
        owner: ${{ inputs.dependency_repo_organization_name }}
        repositories: ${{ inputs.dependency_repo_name }}
    - name: Checkout Dependencies
      uses: actions/checkout@v7
      with:
        repository: '${{ inputs.dependency_repo_organization_name }}/${{ inputs.dependency_repo_name }}'
        token: ${{ steps.app-token.outputs.token }}
        path: ${{ inputs.checkout_path }}
