name: Build and Test
on:
  push:
    branches: [ "ci" ]
env:
  DEPENDENCIES_REPO: sentinels-dependencies
  DEPLOY_PATH: ${{ github.workspace }}/deployed
  ENGINE_DEPS_PATH: ${{ github.workspace }}/ci_deps/libs
  ORGANIZATION_NAME: ${{ github.repository_owner }}
  CAULDRON_MODS_BUILD_FOLDER: CauldronMods/bin/Release/net48
jobs:
  build:
     runs-on: windows-2025-vs2026
     steps:
      - name: Checkout Source Code
        uses: actions/checkout@v7
      - name: Set Up Dependencies'
        uses: ./.github/actions/setup-depedencies-action
        with:
          checkout_path: 'ci_deps'
          dependency_app_id: ${{ secrets.DEP_FETCHER_APP_ID }}
          dependency_private_key: ${{ secrets.DEP_FETCHER_APP_PRIVATE_KEY }}
          dependency_repo_name: ${{ env.DEPENDENCIES_REPO }}
          dependency_repo_organization_name: ${{ env.ORGANIZATION_NAME }}
      - name: Create deployment folder
        run: mkdir -p ${{ env.DEPLOY_PATH }}
      - name: Build the CauldronMods project
        run:  dotnet build CauldronMods/CauldronMods.csproj --configuration Release
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: cauldron-mods-build-artifacts
          path: ${{ env.CAULDRON_MODS_BUILD_FOLDER }}
      - name: Upload Deployment Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: cauldron-mods-deployment-artifacts
          path: ${{ env.DEPLOY_PATH }}
          if-no-files-found: error
  test:
     runs-on: windows-2025-vs2026
     needs: build
     steps:
      - name: Checkout Source Code
        uses: actions/checkout@v7
      - name: Set Up Dependencies'
        uses: ./.github/actions/setup-depedencies-action
        with:
          checkout_path: 'ci_deps'
          dependency_app_id: ${{ secrets.DEP_FETCHER_APP_ID }}
          dependency_private_key: ${{ secrets.DEP_FETCHER_APP_PRIVATE_KEY }}
          dependency_repo_name: ${{ env.DEPENDENCIES_REPO }}
          dependency_repo_organization_name: ${{ env.ORGANIZATION_NAME }}
      - name: Download CauldronMod Build Artifacts
        id: download-build-artifacts
        uses: actions/download-artifact@v4
        with:
          name: cauldron-mods-build-artifacts
          path: ${{ env.CAULDRON_MODS_BUILD_FOLDER }}
      - name: Build the CauldronMods Test Project
        run: dotnet build Testing/Testing.csproj --configuration Release --no-dependencies
      - parallel:
        - name: Run CauldronMods Code Tests
          continue-on-error: true
          run: dotnet test --filter "FullyQualifiedName!~CauldronTests.Art&FullyQualifiedName!~CauldronTests.Oblivaeon&FullyQualifiedName!~CauldronTests.PromoUnlock&FullyQualifiedName!~CauldronTests.Random" --no-build --configuration Release --logger:"console;verbosity=normal;Synchronous=true" --logger "nunit;LogFilePath=test-results/CauldronTests.TestResults.xml" --blame-hang-timeout 20000 -- NUnit.ConsoleOut=0
        - name: Run CauldronMods Art Tests
          continue-on-error: true
          run: dotnet test --filter FullyQualifiedName~CauldronTests.Art --no-build --configuration Release --logger:"console;verbosity=normal;Synchronous=true" --logger "nunit;LogFilePath=test-results/CauldronTests.Art.TestResults.xml" --blame-hang-timeout 20000 -- NUnit.ConsoleOut=0
        - name: Run CauldronMods Oblivaeon Tests
          continue-on-error: true
          run: dotnet test --filter FullyQualifiedName~CauldronTests.Oblivaeon --no-build --configuration Release --logger:"console;verbosity=normal;Synchronous=true" --logger "nunit;LogFilePath=test-results/CauldronTests.Oblivaeon.TestResults.xml" --blame-hang-timeout 20000 -- NUnit.ConsoleOut=0
        - name: Run CauldronMods Promo Unlock Tests
          continue-on-error: true
          run: dotnet test --filter FullyQualifiedName~CauldronTests.PromoUnlock --no-build --configuration Release --logger:"console;verbosity=normal;Synchronous=true" --logger "nunit;LogFilePath=test-results/CauldronTests.PromoUnlock.TestResults.xml" --blame-hang-timeout 20000 -- NUnit.ConsoleOut=0
        - name: Run CauldronMods Random Tests
          continue-on-error: true
          run: dotnet test --filter FullyQualifiedName~CauldronTests.Random --no-build --configuration Release --logger:"console;verbosity=normal;Synchronous=true" --logger "nunit;LogFilePath=test-results/CauldronTests.Random.TestResults.xml" --blame-hang-timeout 20000 -- NUnit.ConsoleOut=0
      - name: Upload Test Reports
        uses: dorny/test-reporter@v3
        if: ${{ !cancelled() }}
        with:
          name: CauldronMod Tests 
          path: Testing/test-results/*.xml
          reporter: dotnet-nunit
